# Carga de Metadatos

En esta sección se muestra un ejemplo para cargar metadatos en Apache Hive a traves de Trino

### Librerias python

Importamos algunas librerias extra que nos ayudan a interactuar con los datos

In [1]:
import trino # Librerias para hacer una conexion JDBC a trino
import pandas as pd # Librerias para presentación de información en formato de tabla

### Definición de la conexión

Definimos la conexión a trino. El catalogo y esquema son opcionales

In [2]:
conn=trino.dbapi.connect(
    host='trino', #URL o IP del servicio de trino
    port=8080, # puerdo donde recibe conexiones el servico Trino
    user='jupyter', # Usuario el cual consumirá la informacion
    #catalog='warehouse', # Catalogo que se desea consultar 
    #schema='lad_enlace24', # Esquema al cual se quiere acceder 
)

## Funciones de ayuda

In [3]:
# Ejecuta la sentencia sql y regresa el resultado, utilizado para creacion de tablas y vistas
def ejecutar_sql(consulta):
    cur = conn.cursor()
    cur.execute(consulta)
    return cur.fetchall()

# Ejecuta la sentencia sql y trae el resultado en forma de tabla de pandas. 
# Se utiliza mayormente en sentancias select
def sql_tabla(consulta):
    cur = conn.cursor()
    cur.execute(consulta)
    valores = cur.fetchall()
    col_names = [x[0] for x in cur.description]
    return pd.DataFrame(valores,columns=col_names)

In [4]:
consulta_crea_tabla = """CREATE TABLE hive.default.ENOEN_SDEM (
	r_def VARCHAR, loc VARCHAR, mun VARCHAR, est VARCHAR,
    est_d_tri VARCHAR, est_d_men VARCHAR, ageb VARCHAR,
    t_loc_tri VARCHAR, t_loc_men VARCHAR, cd_a VARCHAR,
    ent VARCHAR, con VARCHAR, upm VARCHAR, d_sem VARCHAR,
    n_pro_viv VARCHAR, v_sel VARCHAR, n_hog VARCHAR,
    h_mud VARCHAR, n_ent VARCHAR, per VARCHAR, n_ren VARCHAR,
    c_res VARCHAR, par_c VARCHAR, sex VARCHAR, eda VARCHAR,
    nac_dia VARCHAR, nac_mes VARCHAR, nac_anio VARCHAR,
    l_nac_c VARCHAR, cs_p12 VARCHAR, cs_p13_1 VARCHAR, 
    cs_p13_2 VARCHAR, cs_p14_c VARCHAR, cs_p15 VARCHAR,
    cs_p16 VARCHAR, cs_p17 VARCHAR, n_hij VARCHAR, e_con VARCHAR,
    cs_ad_mot VARCHAR, cs_p20_des VARCHAR, cs_ad_des VARCHAR,
    cs_nr_mot VARCHAR, cs_p22_des VARCHAR, cs_nr_ori VARCHAR,
    ur VARCHAR,zona VARCHAR, salario VARCHAR, fac_tri VARCHAR, 
    fac_men VARCHAR, clase1 VARCHAR, clase2 VARCHAR, clase3 VARCHAR,
    pos_ocu VARCHAR, seg_soc VARCHAR, rama VARCHAR, c_ocu11c VARCHAR,
    ing7c VARCHAR, dur9c VARCHAR, emple7c VARCHAR, medica5c VARCHAR,
    buscar5c VARCHAR, rama_est1 VARCHAR, rama_est2 VARCHAR, 
    dur_est VARCHAR, ambito1 VARCHAR, ambito2 VARCHAR, tue1 VARCHAR,
    tue2 VARCHAR, tue3 VARCHAR, busqueda VARCHAR, d_ant_lab VARCHAR,
    d_cexp_est VARCHAR, dur_des VARCHAR, sub_o VARCHAR, 
    s_clasifi VARCHAR, remune2c VARCHAR,pre_asa VARCHAR, 
    tip_con VARCHAR, dispo VARCHAR, nodispo VARCHAR, 
    c_inac5c VARCHAR, pnea_est VARCHAR, niv_ins VARCHAR,
    eda5c VARCHAR, eda7c VARCHAR, eda12c VARCHAR,
    eda19c VARCHAR, hij5c VARCHAR, domestico VARCHAR,
    anios_esc VARCHAR, hrsocup VARCHAR, ingocup VARCHAR,
    ing_x_hrs VARCHAR, tpg_p8a VARCHAR, tcco VARCHAR,
    cp_anoc VARCHAR, imssissste VARCHAR, ma48me1sm VARCHAR,
    p14apoyos VARCHAR, scian VARCHAR, t_tra VARCHAR,
    emp_ppal VARCHAR, tue_ppal VARCHAR, trans_ppal VARCHAR,
    mh_fil2 VARCHAR, mh_col VARCHAR, sec_ins VARCHAR,
    tipo VARCHAR, mes_cal VARCHAR, ca VARCHAR
)
WITH (
    external_location='s3a://hive/ENOEN_SDEM',
    format='CSV',
    skip_header_line_count=1
)
"""

In [5]:
ejecutar_sql(consulta_crea_tabla)

[[True]]

In [6]:
sql_tabla('select * from hive.default.ENOEN_SDEM LIMIT 20')

,r_def,loc,mun,est,est_d_tri,est_d_men,ageb,t_loc_tri,t_loc_men,cd_a,...,t_tra,emp_ppal,tue_ppal,trans_ppal,mh_fil2,mh_col,sec_ins,tipo,mes_cal,ca
0,00,,156,30,0311,0304,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
1,00,,156,30,0311,0304,00000,1,1,81,...,1,2,2,0,3,2,2,1,05,2
2,00,,156,30,0311,0304,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
3,00,,156,30,0311,0304,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
4,00,,156,30,0311,0304,00000,1,1,81,...,1,2,2,0,3,2,2,1,05,2
5,00,,156,30,0311,0304,00000,1,1,81,...,0,0,0,0,0,0,0,1,05,2
6,00,,156,30,0311,0304,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
7,00,,156,30,0311,0304,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
8,00,,156,30,0311,0304,00000,1,1,81,...,1,1,2,0,3,1,4,1,05,2
9,00,,156,30,0311,0304,00000,1,1,81,...,1,2,2,0,3,2,5,1,05,2
10,00,,156,20,0310,0303,00000,1,1,81,...,2,1,2,0,2,1,9,1,05,2
11,00,,156,20,0310,0303,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
12,00,,156,20,0310,0303,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
13,00,,156,20,0310,0303,00000,1,1,81,...,0,0,0,0,0,0,0,1,05,2
14,00,,156,20,0310,0303,00000,1,1,81,...,1,2,2,0,3,2,2,1,05,2
15,00,,156,20,0310,0303,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
16,00,,156,20,0310,0303,00000,1,1,81,...,1,2,2,0,3,2,2,1,05,2
17,00,,156,20,0310,0303,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2
18,00,,156,20,0310,0303,00000,1,1,81,...,1,1,2,0,2,1,9,1,05,2
19,00,,156,20,0310,0303,00000,1,1,81,...,1,0,0,0,0,0,0,1,05,2

In [7]:
sql_tabla('select COUNT(*) as CONTEO from hive.default.ENOEN_SDEM')

    CONTEO
0  1595033

In [8]:
sql_tabla("""select per, COUNT(*) as conteo
from hive.default.ENOEN_SDEM
group by per""")

   per  conteo
0  321  428160
1  221  381319
2  121  350728
3  421  434826

In [ ]:
ejecutar_sql("""drop table hive.default.ENOEN_SDEM""")